guest = ["aunt","uncle","sister"]
print(f"dear{guest[0]} you are invited for our birthday")
print(f"dear{guest[1]} you are invited for our birthday")
print(f"dear{guest[2]} you are invited for our birthday")
print("sister has imfomed she is not attending")
guest.remove(guest[2])
guest.append("niece")
print(f"dear{guest[0]} you are invited for our birthday")
print(f"dear{guest[1]} you are invited for our birthday")
print(f"dear{guest[2]} you are invited for our birthday")
print("dear sister we are so sorry for you please have a pleasant day")
print(f"dear{guest[0]} you are invited for our birthday")
print(f"dear{guest[1]} you are invited for our birthday")
print(f"dear{guest[2]} you are invited for our birthday")
print("dear guests we have found a bigger dinning table we wil invite a few more family members")
guest.insert("brother")
guest.insert("nephew")
guest.insert("grandma")
# guest list
